# default user: postgres
# pass: 1q2w3e4r
version: '3.1'

services:

  db:
    image: postgres:14.1-alpine
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r
