# Use postgres/example user/password credentials
# source: https://hub.docker.com/_/postgres
# get into to container
# >> docker exec -it 3239ecaf53ad sh
# >> psql -U postgresql
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
