# Use root/example as user/password credentials
version: '3.2'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017 # expose outside (on host)
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
